/* It's importing all the files in the folder `basic` */
import './basic/fadeBasic'
import './basic/fadePositionBasic'
import './basic/positionBasic'
import './basic/positionRotateBasic'
import './basic/positionRotateScaleBasic'
import './basic/positionScaleBasic'
import './basic/scaleBasic'
import './animation5'
import './animation-text-wave'
