import './basic/fadeBasic'
import './basic/fadePositionBasic'
import './basic/positionBasic'
import './basic/positionRotateBasic'
import './basic/positionRotateScaleBasic'
import './basic/positionScaleBasic'
import './basic/scaleBasic'